# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'L6Starter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for L6Starter
 pod 'SnapKit'
 pod 'Alamofire'

end
